import type { Metadata } from "next";
import React from "react";
import { Inter } from "next/font/google";
import Header from "../components/Layout/Header";
import "../styles/globals.css";
import Background from "../components/Layout/Background";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html lang="en">
      <body className={`${inter.className} overflow-x-hidden`}>
        <React.Fragment>
          <Header />
          <div className="flex flex-col h-screen">
            <main className="flex-1 w-full flex items-center justify-center">
              {children}
              {/* <Background>{children}</Background> */}
            </main>
          </div>
        </React.Fragment>
      </body>
    </html>
  );
}
